environment:
    global:
        # Your package name
        PACKAGE: "EasyClangComplete"
    matrix:
        - SUBLIME_TEXT_VERSION : "3"

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # Download and run GNUstep installer for Clang/Objective C
    - ps: appveyor DownloadFile "http://ftpmain.gnustep.org/pub/gnustep/binaries/windows/gnustep-core-0.35.0-setup.exe"
    - ps: .\gnustep-core-0.35.0-setup.exe /S
    # install Package Control
    # - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose
